development:
  adapter: mysql2
  host: localhost
  username: root
  password: root
  database: sakura_market_development
  encoding: utf8

test:
  adapter: mysql2
  host: localhost
  username: root
  password: root
  encoding: utf8
  database: sakura_market_test

production:
  adapter: mysql2
  database: sakura_market_production
  pool: 5