# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94fd0f20fbb68972e1f50754dd9df31b68d74ebc5550474fefb7e16d3c10f8d4b4182204e3b8d816003cdd8135593d15f60bb062efc921ee068786eca5bd143c

test:
  secret_key_base: fa97f9d4ed025838987bceadc676e7a131ffac509445bf19b42af6ae602b87aa7ee76e4dfd4c57dd2df500fdee5974b26e4db3177c111c61e49a6254a4c49c12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
